apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-project
spec:
  selector:
    matchLabels:
      app: django-project
  template:
    metadata:
      labels:
        app: django-project
    spec:
      containers:
      - name: django-project
        image: krushilnaik/miniproject4kn:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "512Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: django-project
spec:
  type: ClusterIP
  selector:
    app: django-project
  ports:
  - port: 3000
    targetPort: 3000
